server:
  port: 7075
  servlet:
    context-path: /compass
    session:
      cookie:
        http-only: false
      timeout: 86400

spring:
#  web:
#    locale: en_US
#    #localeResolver: fixed
  messages:
    encoding: UTF-8
    basename: i18n/messages
  application:
    name: task-portal
  profiles:
    active:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/compass?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username:
    password:
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
  opensearch:
    nodes: localhost:9200
    username:
    password:
    truststore:
    truststore-password:
  redis:
    cluster:
      nodes: localhost:6379
    password:
  jackson:
    time-zone: Asia/Shanghai

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

custom:
  opensearch:
    logIndex:
      name: "compass-log-summary"
      shards: 10
      replicas: 2
    appIndex:
      name: "compass-task-app"
      shards: 10
      replicas: 2
    jobIndex:
      name: "compass-job-analysis"
      shards: 10
      replicas: 2
    detectIndex:
      name: "compass-detector-app"
    gcIndex:
      name: "compass-gc-log"
    yarnIndex:
      name: "compass-yarn-app"
    sparkIndex:
      name: "compass-spark-app"
    jobInstanceIndex:
      name: "compass-job-instance"
      shards: 10
      replicas: 2
    flinkReportIndex:
      name: "compass-flink-report"
      shards: 10
      replicas: 2
    flinkTaskAnalysisIndex:
      name: "compass-flink-task-analysis"
      shards: 10
      replicas: 2

  redis:
    logRecordKey: "{lua}:log:record"

  jwt:
    expireDay: 15
    secret: 8ff3bf2c8344

diagnosis:
  flinkPrometheusHost: http://localhost:9090
  flinkPrometheusToken:
  flinkPrometheusDatabase:
